### ISSUE TITLE
NPM start error.

### ISSUE THREAD

**Issue by AlanCh4n** [ZomoXYZ/Discord-Bot-Client#29]
I can't start the application.
Error note:
> botDM@1.0.0 start C:\Users\NAME\Documents\Discord-Bot-Client-master
> electron .

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'C:\Users\syedz\Documents\Discord-Bot-Client-master\node_modules\electron\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! botDM@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the botDM@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NAME\AppData\Roaming\npm-cache\_logs\2020-09-16T07_38_49_154Z-debug.log

===========================
please help ,me

**Comment by Vandesm14** [comment]
@AlanCh4n What shell are you using to perform the command?

**Comment by LolgonHDYT** [comment]
im using the standard windows cmd shell an i get the same error

**Comment by AlanCh4n** [comment]
> @AlanCh4n What shell are you using to perform the command?

I am using Microsoft power shell

**Comment by Vandesm14** [comment]
> I am using Microsoft power shell
Ah nevermind then.

**Comment by AlanCh4n** [comment]
> > I am using Microsoft power shell
> > Ah nevermind then.

why??

**Comment by Vandesm14** [comment]
> > > I am using Microsoft power shell
> > > Ah nevermind then.
> 
> why??

I was getting the same issue but with WSL.
